---
language: go
go:
- tip
- 1.11.x
- 1.10.x
- 1.9.x
- 1.8.x
- "1.7"
- "1.6"
- "1.5"

go_import_path: github.com/dolmen-go/jsonptrerror

before_install:
- go list
- go get -t -v ./...

script:
- go test -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
