---
language: go
go:
- tip
- 1.11.x
- 1.10.x
- 1.9.x
- 1.8.x
- "1.7"
- "1.6"
- "1.5"

env:
# Force use of go.mod for dependencies on Go 1.11
- GO111MODULE=on

go_import_path: github.com/dolmen-go/jsonptrerror

before_install:
- go list
- "if [[ `go version` = 'go version go1.1'[1-9][.\\ ]* ]]; then go list -test ; else go get -t -v ./... ; fi"

script:
- go test -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
